### Collect & load dataset

In [5]:
import pandas as pd

#pd.read_csv('dataset\iris.csv').values # relative path
dataset = pd.read_csv(r'H:\Completed Applications\Iris\assets\dataset\iris.csv').values # absolute path numpy array
print(dataset)


[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [6]:
print(dataset.shape)

(150, 5)


### Definding and reservation labels and features

In [7]:
data = dataset[:,0:4]
target = dataset[:,4]

In [8]:
print(data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [9]:
print(data.shape)

(150, 4)


In [10]:
print(target)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2.]


In [11]:
print(target.shape)

(150,)


### Proformance evaluation

In [14]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target = train_test_split(data,target,test_size=0.2) # 20% for testing (150 -> 20% = 30) 

In [15]:
print(train_data,train_data.shape)

[[5.4 3.9 1.3 0.4]
 [7.7 2.8 6.7 2. ]
 [5.2 3.4 1.4 0.2]
 [6.7 3.1 4.7 1.5]
 [5.8 2.6 4.  1.2]
 [5.8 2.7 5.1 1.9]
 [5.5 3.5 1.3 0.2]
 [5.4 3.4 1.7 0.2]
 [5.7 2.9 4.2 1.3]
 [6.3 2.8 5.1 1.5]
 [5.5 2.4 3.7 1. ]
 [7.1 3.  5.9 2.1]
 [6.3 2.5 5.  1.9]
 [6.4 2.9 4.3 1.3]
 [6.  3.  4.8 1.8]
 [5.6 3.  4.5 1.5]
 [5.7 2.5 5.  2. ]
 [5.6 2.9 3.6 1.3]
 [4.8 3.  1.4 0.3]
 [6.9 3.2 5.7 2.3]
 [6.1 2.6 5.6 1.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [7.4 2.8 6.1 1.9]
 [6.6 2.9 4.6 1.3]
 [5.2 4.1 1.5 0.1]
 [5.9 3.  4.2 1.5]
 [5.  3.  1.6 0.2]
 [6.5 3.2 5.1 2. ]
 [6.  2.7 5.1 1.6]
 [5.6 3.  4.1 1.3]
 [7.2 3.6 6.1 2.5]
 [6.1 2.8 4.7 1.2]
 [5.1 3.7 1.5 0.4]
 [5.6 2.7 4.2 1.3]
 [5.4 3.  4.5 1.5]
 [5.8 2.7 5.1 1.9]
 [5.8 2.7 4.1 1. ]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 2.8 4.6 1.5]
 [6.2 2.9 4.3 1.3]
 [5.7 2.6 3.5 1. ]
 [6.6 3.  4.4 1.4]
 [6.3 2.9 5.6 1.8]
 [5.9 3.  5.1 1.8]
 [7.7 3.8 6.7 2.2]
 [6.  3.4 4.5 1.6]
 [6.9 3.1 4.9 1.5]
 [6.2 3.4 5.

In [16]:
print(train_target,train_target.shape)

[0. 2. 0. 1. 1. 2. 0. 0. 1. 2. 1. 2. 2. 1. 2. 1. 2. 1. 0. 2. 2. 1. 0. 2.
 2. 1. 0. 1. 0. 2. 1. 1. 2. 1. 0. 1. 1. 2. 1. 0. 0. 2. 2. 1. 1. 1. 1. 2.
 2. 2. 1. 1. 2. 1. 0. 0. 2. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 2.
 2. 1. 1. 2. 0. 2. 1. 2. 1. 0. 0. 0. 0. 0. 1. 0. 2. 1. 2. 0. 0. 0. 2. 0.
 2. 0. 0. 0. 2. 1. 2. 2. 1. 2. 1. 2. 0. 2. 2. 2. 0. 1. 1. 0. 0. 0. 1. 0.] (120,)


In [17]:
print(test_data,test_data.shape)

[[4.9 2.5 4.5 1.7]
 [5.7 3.8 1.7 0.3]
 [6.4 2.7 5.3 1.9]
 [6.5 3.  5.2 2. ]
 [6.7 3.  5.  1.7]
 [6.7 3.1 5.6 2.4]
 [7.3 2.9 6.3 1.8]
 [5.7 2.8 4.1 1.3]
 [5.3 3.7 1.5 0.2]
 [6.7 3.3 5.7 2.1]
 [4.4 2.9 1.4 0.2]
 [6.3 2.7 4.9 1.8]
 [5.1 3.8 1.5 0.3]
 [5.  3.4 1.6 0.4]
 [6.1 3.  4.9 1.8]
 [5.7 3.  4.2 1.2]
 [4.8 3.4 1.9 0.2]
 [6.2 2.2 4.5 1.5]
 [4.8 3.4 1.6 0.2]
 [6.3 3.3 6.  2.5]
 [6.7 3.1 4.4 1.4]
 [4.9 3.6 1.4 0.1]
 [5.  3.6 1.4 0.2]
 [6.9 3.1 5.4 2.1]
 [5.  3.3 1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [6.4 2.8 5.6 2.1]
 [5.6 2.8 4.9 2. ]
 [4.9 2.4 3.3 1. ]
 [4.6 3.1 1.5 0.2]] (30, 4)


In [18]:
print(test_target,test_target.shape)

[2. 0. 2. 2. 1. 2. 2. 1. 0. 2. 0. 2. 0. 0. 2. 1. 0. 1. 0. 2. 1. 0. 0. 2.
 0. 1. 2. 2. 1. 0.] (30,)


### Load the KNN algorithm

In [19]:
from sklearn.neighbors import KNeighborsClassifier # loading the KNN class

model = KNeighborsClassifier() # loading the KNN algorithm (object from KNN class)

### Traning a algorithm

In [20]:
model.fit(train_data,train_target) # training the algorithm

KNeighborsClassifier()

### Get predictions (algorithm evaluation)

In [21]:
predicted_target = model.predict(test_data) # getting predictions
print(predicted_target)

[1. 0. 2. 2. 1. 2. 2. 1. 0. 2. 0. 2. 0. 0. 2. 1. 0. 1. 0. 2. 1. 0. 0. 2.
 0. 1. 2. 2. 1. 0.]


In [22]:
print(test_target)

[2. 0. 2. 2. 1. 2. 2. 1. 0. 2. 0. 2. 0. 0. 2. 1. 0. 1. 0. 2. 1. 0. 0. 2.
 0. 1. 2. 2. 1. 0.]


 ### Proformance measure (get accuracy score)

In [23]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(test_target,predicted_target)
print('acc:',acc)

acc: 0.9666666666666667


In [24]:
30*0.933

27.990000000000002

### Get training accuracy

In [25]:
predicted_train_target = model.predict(train_data)

In [26]:
train_acc = accuracy_score(train_target,predicted_train_target)
print('train acc:',train_acc)

train acc: 0.975


### Save model

In [27]:
import joblib

joblib.dump(model,'KNN-iris-model')

['KNN-iris-model']